index:
  path: /
  controller: App\Controller\DefaultController::index


logIn:
  path: /logIn
  controller: App\Controller\UserController::connexion

deco:
  path: /deco
  controller: App\Controller\UserController::deco
